language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
  - os: linux
    dist: trusty
    compiler: clang
  - os: osx
    osx_image: xcode8.3
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which cmake || brew update        ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which cmake || brew install cmake ; fi
before_script:
- cd $TRAVIS_BUILD_DIR/..
- git clone -b master https://github.com/xbmc/xbmc.git
- mkdir -p addons/pvr.zattoo
- mkdir pvr.zattoo/build && cd pvr.zattoo/build
- if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc" ]]; then export CC=gcc-5; export CXX=g++-5; fi
- cmake -DADDONS_TO_BUILD="pvr.zattoo" -DCMAKE_INSTALL_PREFIX=install -DPACKAGE_ZIP=ON -DADDONS_DEFINITION_DIR=$TRAVIS_BUILD_DIR/../addons $TRAVIS_BUILD_DIR/../xbmc/cmake/addons -DADDON_SRC_PREFIX=$TRAVIS_BUILD_DIR/..
script: make package-pvr.zattoo
